# Base configs
baseurl: "https://joshuarhall.github.io/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Josh Hall"
subtitle: "See the world through my eyes!"
author: "Josh Hall"
header:
 title: "Photography"
 subtitle: "by Josh Hall"
footer:
 name: "Hey there, my name is Josh"
 bio: "I am a hobbyist photographer. I shoot mostly 35mm film with my Pentax cameras, 120 film on my Yashica Mat 124-G, and Sony a7ii cameras."
web_design: "AJ" and <a href=\"https://www.twitter.com/ram__patra\">Ram Patra<a>
social_urls:
  twitter: "https://www.twitter.com/joshuarhall"
  instagram: "https://www.instagram.com/joshuarhall"
  linkedin: "https://www.linkedin.com/in/joshuarhall0/"
  github: "https://www.github.com/joshuarhall"
